language: node_js
script: npm run-script test-travis
node_js:
- '0.10'
- '0.11'
after_script: npm install coveralls@2.10.0 && cat ./coverage/lcov.info | coveralls
deploy:
  provider: npm
  email: tituswormer@gmail.com
  api_key:
    secure: KXkqBWFA1hURRMED+aPrhXu3F3SReytw4GcAlqSVQOb9bAOVG54RiKFmJbjqfDjcMHXxqptnGWG+tifBa9SJjFeHaDKaXcyyyyiW2PTHkkS+mR8zuewZO6cpFgWAPDe+nHEtlE1/21DYBI9sot9sX9xTxcY8Fqb03/fndfQOAHA=
  on:
    repo: wooorm/textom-link-node
